apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-dev
  labels:
    env: dev
spec:
  containers:
  - name: nginx-container
    image: nginx:latest
    ports:
    - containerPort: 80
      protocol: TCP
