apiVersion: v1
kind: Pod
metadata:
  name: tmkube-pod-dev
spec:
  containers:
    - name: container
      image: tmkube/init
      envFrom:
        - configMapRef:
            name: tmkube-cm-dev
        - secretRef:
            name: tmkube-secret-dev