apiVersion: v1
kind: Service
metadata:
  name: http-request
spec:
  type: NodePort
  selector:
    app: http-request
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 30080